final changes
Mukumbuta/ZOO_Animals_Data pull request #1
Opened 2022-10-22 19:26 UTC by Mukumbuta

# About this PR:

## Interactions

### Home page
- When the page loads, the web app shows the list of animals that can be filtered out by any character contained in the names of the animals
- Along with the category name, some numeric values that come from the API are displayed per category
- When the user clicks (or taps) on a category item, the application navigates to the details page

### Details page
- In the details page, the web app retrieves data from the API to show detailed data in the category.
- When the user clicks on the "Back" button (<), the user navigates to the home page

### Testing requirements
- Created unit tests for pure functions in the Redux code
- Created integration tests for the application using the React Testing Library
- Mocked the access to the API, so that the tests don't send actual requests

### Technical requirements
- The project is a single-page application (SPA) built with React and Redux 👍🏾
- The data retrieved from the API should be stored in the Redux store 👍🏾
- You should filter the data that you retrieve from the API using a Filter stateless component 👍🏾
- Every page (the main page and the pages for each item) should have a unique route within the SPA 👍🏾
- The project should be deployed and accessible online (add a link to the online version of your app to your README file) 👍🏾

### Project documentation
- Record a video presenting the features of the project you built 👍🏾

2022-10-23 00:51 UTC, OLIPLICHE requested changes
Hi @Mukumbuta, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linter is green (the last commit have a green check mark (✅)) 👏
- Commit messages are meaningful 👏 👏
- Gitflow is correctly used (Pull Request is made from the feature branch into the dev branch) 👏

## Required Changes ♻️
- Please make sure the video contains a highlight about a **piece of the code** that you find interesting or are proud of making.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-23 00:51 UTC, OLIPLICHE commented on README.md
> +- Nelson Sakwa on whose original design this project is based.
- You did a good Job, You mentioned Nelson Sakwa. Now you need to Link it to the main website design. 
- I Provide the Link in acknowledging Nelson Sakwa. here is the link:  👉 [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-10-23 00:51 UTC, OLIPLICHE commented on README.md
> +```
- **Optional**: Kindly remove this dot of lines to make the sections below look better and more visible. 
- **Optional**: Also the images you provided in Home section page and Details page section are broken, Kindly fix that

2022-10-23 00:51 UTC, OLIPLICHE commented on package.json
> +  },
- Please can't run the App. I think you have an issue with your package.json. Kindly check your setup
- I cross-check at my end. I did not work
![1](https://user-images.githubusercontent.com/63972670/197367845-bd6ac571-dce2-4ae0-ba7d-add88b16a439.JPG)

2022-10-23 00:51 UTC, OLIPLICHE commented on src/_test_/Animal.test.js
> +      .toJSON();
- Test 
- 
![Capture1](https://user-images.githubusercontent.com/63972670/197367859-1587cddb-c872-4281-b00a-4564f16c1f3b.JPG)

2023-01-12 12:09 UTC, FrederickMih approved these changes
## Hi :raising_hand:  @Mukumbuta, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights :green_circle: 

- Great app design :+1: 
- Descriptive README.md file :+1: 
- PR is professional :+1: 
- All Linter checks passed :heavy_check_mark: 

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-01-12 12:09 UTC, FrederickMih commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [Optional] The License link is not working. Let's kindly fix the link :+1:

2023-01-12 12:09 UTC, FrederickMih commented on README.md
> +# 📖 [CMS_Bookstore] <a name="about-project"></a>
- [Opitonal] Please correct the title of your project.

2023-01-12 12:09 UTC, FrederickMih commented on src/API/api.js
> +const ANIMALS_FETCHED = 'ANIMALS_FETCHED';
- [Optional] To easily scale your app in the future, it's advisable to scope your action types using Redux [duck pattern](https://medium.com/@matthew.holman/what-is-redux-ducks-46bcb1ad04b7)

2023-01-12 12:09 UTC, FrederickMih commented on src/component/Animal.js
> +            }
- [Optional] Filter works perfectly :+1:  but based on the requirement of this project, this was supposed to be achieved on a component that holds **no state**( **Filter** stateless component).

2023-01-12 12:09 UTC, FrederickMih commented on src/component/Animal.js
> +          // eslint-disable-next-line
- [Optional] Please let's fix all the Linter issues across codebase. Linters flag bugs that are required to fix in order to keep your codebase at standard.

2023-02-09 13:45 UTC, merged